name: AdvancedBan
version: 2.0.6
author: Leoko
main: me.leoko.advancedban.BukkitMain

commands:
  AdvancedBan:
    description: Information about the Plugin
  ban:
    description: Ban a user permanently
  tempban:
    description: Ban a user temporarily
  ipban:
    description: Ban a user by IP
    aliases: [banip, ban-ip]
  kick:
    description: Kick a user
  warn:
    description: Warn a user permanently
  tempwarn:
    description: Warn a user temporarily
  mute:
    description: Mute a user permanently
  tempmute:
    description: Mute a user temporarily
  banlist:
    description: See all punishments
  history:
    description: See a user''s history
  warns:
    description: See your or a user''s warns
  check:
    description: Get all information about a user
  systemPrefs:
    description: Displays System-Preferences for setting up the plugin
  unwarn:
    description: Deletes a warn
  unpunish:
    description: Deletes a punishment by ID
  unban:
    description: Unban a user
  unmute:
    description: Unmute a user
